//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressTranslatorModelContainer : DbContext
    {
        public AddressTranslatorModelContainer()
            : base("name=AddressTranslatorModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Address> AddressSet { get; set; }
        public virtual DbSet<AddressCreateInfo> AddressCreateInfoSet { get; set; }
        public virtual DbSet<NameComponent> NameComponentSet { get; set; }
        public virtual DbSet<Language> LanguageSet { get; set; }
        public virtual DbSet<NameType> NameTypeSet { get; set; }
        public virtual DbSet<NameTree> NameTreeSet { get; set; }
        public virtual DbSet<TreePointer> TreePointerSet { get; set; }
    }
}
