//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string Name { get; private set; }
        public System.Guid IP { get; set; }
        public bool IPv6 { get; set; }
    
        public virtual AddressCreateInfo AddressCreateInfo { get; set; }
    }
}
